module.exports = {
  mongoUri: process.env.MONGO_URI,
  adminUrl: process.env.ADMIN_URL,
  uploadPath: process.env.UPLOAD_PATH,
  tempUploadPath: process.env.TEMP_UPLOAD_PATH,
  imageBase: process.env.IMAGE_BASE,
  host: process.env.HOST,
  imageUrl: process.env.IMAGE_URL,
  adminImageUrl: process.env.ADMIN_IMAGE_URL,
  secret: process.env.SESSION_SECRET,
  maxAge: Number(process.env.SESSION_MAX_AGE),
  basePassword: process.env.BASE_PASSWORD,
  snsUserTopic: process.env.SNS_USER_TOPIC,
  snsBusinessTopic: process.env.SNS_BUSINESS_TOPIC,
  adminPort: process.env.ADMIN_PORT,
  port: process.env.PORT,
  smtpFrom : process.env.SMTP_FROM,
  smtpHost : process.env.SMTP_HOST,
  smtpService : process.env.SMTP_SERVICE,
  smtpAuthUser: process.env.SMTP_AUTH_USER,
  smtpAuthPass: process.env.SMTP_AUTH_PASS,
  fromMail: process.env.FROM_MAIL,
};
